# Generated by Django 3.1.3 on 2020-11-13 11:59

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_streamfieldblogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamfieldblogpost',
            name='content',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock()), ('premium_paragraph', wagtail.core.blocks.RichTextBlock()), ('discovery_url', wagtail.core.blocks.TextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('youtube_video', wagtail.embeds.blocks.EmbedBlock())]),
        ),
    ]
